# Generated by Django 6.0.2 on 2026-05-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccon_messages', '0006_message_delete_reason_message_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
